### PR TITLE
reduce dependent libraries Docker image size

### PR DESCRIPTION
**Pull request by dalisoft**
[This](https://github.com/dalisoft/nanoexpress#credits) uses this library and it's very great that you're build this. Thank you for awesome work.

Also, my [uWebSockets.js dev-env template](https://github.com/dalisoft/uwebsockets-dev-env) uses this library.

But you can some patch for me (and for future of both my and your library)?

This one-line (oh, diff makes it 3-line) patch reduces ~10Mb Dockerfile which great reduction.

### CODE REVIEW

**Comment by dalisoft** [comment]
Seems failed due of permission issue :(

**Comment by aadityataparia** [comment]
You already have uwebsockets as dependency in package.json, try removing that and see if that makes any difference? As uwebsockets is already installed by sift/server.

**Comment by dalisoft** [comment]
@aadityataparia I think using `peerDependencies` is good solution for both libraries =)

**Comment by aadityataparia** [comment]
@dalisoft Hmm, seems fare! I will commit needed changes tomorrow, thanks for the pr.

**Pull request merged**
